### ISSUE TITLE
Purpose of some code lines unclear

### ISSUE THREAD

**Issue by m99coder** [cedricdelpoux/gatsby-plugin-translate-urls#10]
Hi Cédric,

I wanna ask if you could clarify the purpose of [these code lines](https://github.com/cedricdelpoux/gatsby-plugin-translate-urls/blob/master/utils/translate-url.js#L16-L24) in `/utils/translate-url.js`:

```js
if (pathLocale && pathLocale !== locale) {
  const newPath = "/" + locale

  if (isDefaultLocale) {
    return removeLocaleFromPath(newPath, defaultLocale)
  }

  return newPath
}
```

The background is that I try to prepare [a PR](https://github.com/cedricdelpoux/gatsby-plugin-translate-urls/compare/master...m99coder:add-tests) for your really nice and valuable plugin to add tests and can’t get my head around the purpose of these lines. Currently the test cases return these values:

```
translateUrl({
  path: "/en/english",
  locale: "fr",
  translations: {en: {english: "english"}, fr: {english: "français"}},
})
// "/fr"

translateUrl({
  path: "/en/english",
  locale: "fr",
  translations: {en: {english: "english"}, fr: {english: "français"}},
  defaultLocale: "fr",
})
// "/"
```

My assumption was that:

- `/en/english` (without `defaultLocale`) gets translated into `/fr/français`
- `/en/english` (with `defaultLocale` as `fr`) gets translated into `/français`

It would be really helpful if you could explain your thoughts on that part of your code.

All the best,
Marco

**Comment by cedricdelpoux** [comment]
Hi Marco, 

For what I read, you understood pretty well what the plugin attempt to achieve. Maybe this part of code is not used anymore.

Please make sure that the demo keep the same behavior. And if the code is dead, you can remove it.

Thank you for helping introducing tests. It will be very helpful!

**Comment by m99coder** [comment]
The purpose is to fallback to locale root in case there is no translated page.
